export class AbacError extends Error { constructor(code, message) { super(message); this.code = code; } }
const requireRole = (actor, role) => { if (actor.role !== role) throw new AbacError('FORBIDDEN', 'The actor is not authorized for this supplier ABAC policy transition.'); };
export function createAbacPolicyRegistry() {
  const policies = new Map(); const proposals = new Map(); const audit = [];
  const record = (action, policyId, actor, detail = {}) => audit.push({ id: `AUD-${audit.length + 1}`, action, policyId, actor, detail, at: new Date().toISOString() });
  const get = id => { const policy = policies.get(id); if (!policy) throw new AbacError('NOT_FOUND', 'The supplier ABAC policy was not found.'); return policy; };
  const validRule = rule => rule && typeof rule === 'object' && ['region', 'tier', 'purpose'].every(key => typeof rule[key] === 'string' && rule[key].length > 0);
  return {
    define(actor, input) { requireRole(actor, 'policy-engineer'); if (!/^ABAC-[A-Z0-9]{3,}$/.test(input.id || '') || !input.supplier || !validRule(input.rule) || !input.action || input.action.trim().length < 3) throw new AbacError('VALIDATION', 'Identifier, supplier, action, and complete attribute rule are required.'); if (policies.has(input.id)) throw new AbacError('CONFLICT', 'The supplier ABAC policy identifier already exists.'); const policy = { id: input.id, supplier: input.supplier.trim(), action: input.action.trim(), rule: { ...input.rule }, state: 'draft' }; policies.set(policy.id, policy); record('policy.defined', policy.id, actor.id); return { ...policy, rule: { ...policy.rule } }; },
    proposeActivation(actor, id, evidence) { requireRole(actor, 'supplier-manager'); const policy = get(id); if (policy.state !== 'draft') throw new AbacError('CONFLICT', 'Only draft supplier ABAC policies can request activation.'); if (!evidence || evidence.trim().length < 30) throw new AbacError('VALIDATION', 'Attribute policy evidence must be at least 30 characters.'); const proposal = { id: `PROP-${proposals.size + 1}`, policyId: id, evidence: evidence.trim(), state: 'requested', requestedBy: actor.id }; proposals.set(proposal.id, proposal); policy.state = 'pending'; record('activation.requested', id, actor.id, { proposalId: proposal.id }); return { ...proposal }; },
    approve(actor, proposalId) { requireRole(actor, 'policy-governor'); const proposal = proposals.get(proposalId); if (!proposal) throw new AbacError('NOT_FOUND', 'The ABAC policy activation proposal was not found.'); if (proposal.state !== 'requested') throw new AbacError('CONFLICT', 'The ABAC policy activation proposal has already been decided.'); proposal.state = 'approved'; proposal.approvedBy = actor.id; get(proposal.policyId).state = 'active'; record('activation.approved', proposal.policyId, actor.id, { proposalId }); return { ...proposal }; },
    evaluate(actor, id, context) { requireRole(actor, 'policy-runtime'); const policy = get(id); if (policy.state !== 'active') throw new AbacError('CONFLICT', 'Only active supplier ABAC policies can evaluate access.'); if (!context || !context.attributes || typeof context.attributes !== 'object') throw new AbacError('VALIDATION', 'A subject attribute context is required.'); const allowed = context.action === policy.action && Object.entries(policy.rule).every(([key, value]) => context.attributes[key] === value); record(allowed ? 'evaluation.allowed' : 'evaluation.denied', id, actor.id, { subjectId: context.subjectId || 'unknown' }); return { allowed }; },
    retire(actor, id, reason) { requireRole(actor, 'policy-governor'); const policy = get(id); if (policy.state !== 'active') throw new AbacError('CONFLICT', 'Only active supplier ABAC policies can be retired.'); if (!reason || reason.trim().length < 15) throw new AbacError('VALIDATION', 'A detailed ABAC policy retirement reason is required.'); policy.state = 'retired'; record('policy.retired', id, actor.id, { reason: reason.trim() }); return { ...policy, rule: { ...policy.rule } }; },
    get: id => { const policy = get(id); return { ...policy, rule: { ...policy.rule } }; }, audit: () => audit.map(item => ({ ...item })), count: () => policies.size
  };
}
